# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3aed376b1ae826d851a8d34918b2aa2d16c8b83ac2f8de4074ea4143888cccd15f9b9cb6f9c53e714380a7fbfdb3853e7d36ed66ceecfa02b331c14d7d998448

test:
  secret_key_base: d1079c2be4acbb3b0a83e7de8c05649898347b0a7d941d2f93ccca585685590e6d36d26452a730bb901a552f052dcac20ceb0de4ac3b5f4bad8876303b0268b8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
